### ISSUE TITLE
[LOC]Document(ja-jp) is not translated. 

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windowsserverdocs.ja-jp#20]
![tsecimp_1_j](https://user-images.githubusercontent.com/40815708/61181940-c6489a80-a667-11e9-88f6-2a633a09f8cc.png)

https://docs.microsoft.com/ja-jp/windows-server/administration/windows-commands/tsecimp_1

same page:"https://github.com/MicrosoftDocs/windowsserverdocs.ja-jp/pull/19"

**Comment by lichasu** [comment]
Hello, @hyoshioka0128 

Your contribution is much appreciated. Our team reviewed your feedback and it appears that this issue has been already logged. 

Please review issue #https://github.com/MicrosoftDocs/windowsserverdocs.ja-jp/pull/19 . For this reason we are closing this issue since it is duplicated. 

Kind regards, 
Microsoft DOCS International Team
